/**
 * Reply presets: the tone row above the reply box, and what the user may do to
 * it.
 *
 * Kept out of `settings.ts` for the reason `models.ts` is: that file imports
 * WXT's `#imports`, which resolves only inside a build, and this table has to
 * be readable by the eval scripts under plain tsx. The storage item that holds
 * the user's changes lives in `settings.ts`; everything here is arithmetic over
 * a value someone else read.
 *
 * ## A preset says how loud to be, not who you are
 *
 * That line is the whole design problem (#6). The soul profile says who the
 * person is; a preset modifies one reply. Given a free text box people will
 * write a second soul into a preset — "I'm a woodworker, be friendly, mention
 * my Etsy" — and then two parts of the prompt describe the same thing and the
 * model follows whichever sits lower. The editor says so, the placeholder is a
 * tone instruction rather than an empty box, and `LIMITS.text` is small enough
 * that a profile does not fit in one.
 *
 * ## What the prompt measurements dictate here
 *
 * Three findings from `npm run eval`, each a constraint rather than advice:
 *
 * - **`auto` carries no text and must never be given any.** Its old line said
 *   to match the tone of the comment, which is what the model does when nothing
 *   is said at all: removing it changed neither reply length nor how often a
 *   reply merely restated the comment. It survives as the row's off switch, and
 *   is excluded from editing so nobody can resurrect the dead line.
 * - **Every preset line is billed on every reply it is used for.** A paragraph
 *   typed in here is paid for again on each press, which is why `LIMITS.text`
 *   is 120 characters against the longest built-in's 51.
 * - **Instructions are obeyed maximally.** "Speak from yourself" produced
 *   first-person in 89% of replies against 31% for real creators, so a preset
 *   reading "be funny" makes every reply a joke. The editor says this in a line
 *   of help text rather than leaving it to be discovered.
 */

/** The row's off switch. Always present, never edited, never hidden. */
export const AUTO = 'auto';

/**
 * The presets that ship, in the order they ship in.
 *
 * `auto` first because it is the default. Its empty text is not an oversight:
 * an empty preset adds no line to the prompt, which is what "no preset" has to
 * mean once the table is editable.
 */
export const BUILT_IN: ReadonlyArray<{ id: string; name: string; text: string }> = [
  { id: AUTO, name: 'auto', text: '' },
  { id: 'friendly', name: 'friendly', text: 'Be warm and welcoming.' },
  { id: 'humorous', name: 'humorous', text: 'Be light-hearted. Land the joke without forcing it.' },
  { id: 'engaging', name: 'engaging', text: 'Invite a reply. Ask something worth answering.' },
  { id: 'brief', name: 'brief', text: 'Answer in one short sentence.' },
];

/**
 * What the row is allowed to grow to.
 *
 * `text` is the one that matters and it is deliberately mean — see the billing
 * note above. `name` is bounded by the chip it has to fit inside, and `presets`
 * by `chrome.storage.sync`: twelve entries at these lengths is about 2 KB
 * against sync's 8 KB per item, which leaves the limit comfortable rather than
 * something a user can walk into.
 */
export const LIMITS = { name: 24, text: 120, presets: 12 } as const;

/**
 * The user's changes, as deviations rather than as a copy of the table.
 *
 * A copy would freeze today's wording the moment somebody renamed one preset,
 * and "restore this to the original" would need the original kept anyway. As an
 * overlay, restoring is deleting a key, and a better sentence shipped in a
 * future version still reaches everyone who never edited that preset.
 */
export interface PresetOverlay {
  /**
   * Display order, by id. Ids missing from it keep their natural order after
   * the ones listed, so a preset added in a later version appears rather than
   * vanishing behind an exhaustive list written by an older build.
   */
  order?: string[];
  /** Ids kept out of the row. `AUTO` is ignored here — see `readPresets`. */
  hidden?: string[];
  /** Changes to built-ins, by id. Absent keys mean untouched. */
  edits?: Record<string, { name?: string; text?: string }>;
  /** Presets the user added. Ids are generated by `newPresetId`. */
  custom?: Array<{ id: string; name: string; text: string }>;
}

export interface Preset {
  id: string;
  name: string;
  /** The sentence handed to the model. Empty adds no line at all. */
  text: string;
  /** One of `BUILT_IN`: it can be restored and hidden, but never deleted. */
  builtIn: boolean;
  hidden: boolean;
  /** A built-in whose name or text was changed, and so has something to restore. */
  edited: boolean;
}

/**
 * The whole row, in display order, hidden entries included.
 *
 * One function for both readers on purpose: the popover filters to the visible
 * ones and the editor shows all of them, and a second traversal with its own
 * ordering rules is how the two would drift apart.
 */
export function readPresets(overlay: PresetOverlay | null): Preset[] {
  const edits = overlay?.edits ?? {};
  // `AUTO` is filtered out rather than trusted: nothing in the editor can hide
  // it, but storage is a place a value can arrive from sync written by a build
  // that did not know that — and a row with everything hidden has no chips.
  const hidden = new Set((overlay?.hidden ?? []).filter((id) => id !== AUTO));

  const presets: Preset[] = BUILT_IN.map((preset) => {
    // `auto` is not editable, so an edit that somehow reached storage for it is
    // dropped here rather than shown. Named explicitly because this is the one
    // rule the measurements are behind.
    const edit = preset.id === AUTO ? undefined : edits[preset.id];

    return {
      id: preset.id,
      name: edit?.name ?? preset.name,
      text: edit?.text ?? preset.text,
      builtIn: true,
      hidden: hidden.has(preset.id),
      edited: Boolean(edit && (edit.name !== undefined || edit.text !== undefined)),
    };
  });

  for (const preset of overlay?.custom ?? []) {
    presets.push({ ...preset, builtIn: false, hidden: hidden.has(preset.id), edited: false });
  }

  return sortByOrder(presets, overlay?.order);
}

/** Only what the chip row shows. */
export function visiblePresets(overlay: PresetOverlay | null): Preset[] {
  return readPresets(overlay).filter((preset) => !preset.hidden);
}

/**
 * The line to put in the prompt for the chosen preset.
 *
 * Empty for `auto`, for a preset that was hidden or deleted since it was
 * chosen, and for one whose text was emptied. All four mean the same thing to
 * the prompt — add nothing — which is why the caller gets a string rather than
 * a preset and never has to special-case the id.
 */
export function toneFor(overlay: PresetOverlay | null, id: string): string {
  const chosen = visiblePresets(overlay).find((preset) => preset.id === id);
  return chosen ? chosen.text.trim() : '';
}

/**
 * Which preset the row should show as chosen.
 *
 * A stored id can outlive the preset it names — the one it pointed at was
 * hidden on another machine, or deleted here while a popover was open. Falling
 * back to `AUTO` keeps a row that always has exactly one chip lit; leaving the
 * dangling id selected would light none and look broken.
 */
export function selectedPreset(overlay: PresetOverlay | null, id: string): string {
  return visiblePresets(overlay).some((preset) => preset.id === id) ? id : AUTO;
}

/** An id for a preset the user just added. Short, and unique against a clock. */
export function newPresetId(): string {
  return `c${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`;
}

/** Trim and cut to the cap. Applied on write, so storage never holds an overlong value. */
export function clamp(value: string, limit: number): string {
  const trimmed = value.trim();
  return trimmed.length > limit ? trimmed.slice(0, limit).trimEnd() : trimmed;
}

/**
 * Put the listed ids first, in the order given, and everything else after.
 *
 * The tail is what makes the order forward-compatible: a build that ships a
 * sixth built-in finds it missing from an order written by the fifth, and it
 * lands at the end of the row instead of disappearing from it.
 */
function sortByOrder(presets: Preset[], order?: string[]): Preset[] {
  if (!order || order.length === 0) return presets;

  const rank = new Map(order.map((id, index) => [id, index]));
  return [...presets].sort((a, b) => {
    const left = rank.get(a.id) ?? Number.MAX_SAFE_INTEGER;
    const right = rank.get(b.id) ?? Number.MAX_SAFE_INTEGER;
    return left - right;
  });
}
