import { defineConfig } from 'wxt';
import tailwindcss from '@tailwindcss/vite';
import { remToPx } from './build/rem-to-px';

// See https://wxt.dev/api/config.html
export default defineConfig({
  modules: ['@wxt-dev/module-react'],

  vite: (env) => ({
    plugins: [tailwindcss(), remToPx()],

    oxc: {
      jsx: {
        // Vite 8 transforms JSX with oxc, and @vitejs/plugin-react does not set
        // `development` — oxc then defaults to the dev transform even in a
        // production build. That emits `jsxDEV()` calls, but React's
        // `jsx-dev-runtime` is an empty stub once NODE_ENV is production, so
        // every component throws "jsxDEV is not a function" on first render.
        // The dev transform also bakes absolute source paths into the bundle.
        development: env.mode !== 'production',
      },
    },
  }),

  manifest: (env) => ({
    // "YouTube" is a trademark, and Google's branding guidelines forbid building
    // it into the name of an application — "for YouTube" as a description of the
    // relationship is the phrasing they allow. The Web Store rejects on
    // trademark, and the item name is the field it looks at first.
    name: 'Reply AI — AI replies for YouTube comments',
    description:
      'Draft replies to YouTube comments in your own voice. Free trial included, then your own OpenRouter key.',
    version: '1.0.1',

    // Pins the extension ID to lbldodejinpgfnoaficdhaglkbhnkmlb during
    // development. Without this an unpacked extension's ID is derived from its
    // directory path, and the OAuth redirect URL
    // (https://<id>.chromiumapp.org/) would change with it.
    // Generated by scripts/generate-key.mjs; the private half lives in .keys/.
    //
    // Left out of production builds on purpose: the Web Store assigns the
    // published item its own permanent ID, and a package arriving with a key of
    // ours claims an ID the store did not give it. The published ID is only
    // knowable after the first upload — it lands in EXTENSION_ID in
    // lib/feedback.ts and in the site's links.ts, alongside the IN_STORE flags.
    ...(env.mode === 'production'
      ? {}
      : {
          key: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2ux27q6d25ii39Jjk8EBogWJ3M0DtFCUAWrKo9jWJmluilWMF0VcnYa/7dEHNONJ7P14lwRc7GichBksk0LH3/y44pQyBvk5kimdnaAgpgtrBrhEHTOZlP8tfhS8A78RQc9G8mDlPr2ctJHrUXYOz+VUrYuViLZvCWJnxI3O3y0C5MCA+rcb7bSGcfXj1Gy2jRgkrHsH6aTQRD5mY0qQYtk1qHMq/Fd06hM5Ne3//ulKRqKTFzghK/Z6bqu5VxtGxRBtMm8RQiCTS031kpnVluzetvzXxLc84BKEJNtsS95W4bnHCzzvOGVqvM1ki/A20yd2wJ6Egrq9rnBYb7ICsQIDAQAB',
        }),

    // `identity` is needed for the OpenRouter OAuth PKCE flow via
    // chrome.identity.launchWebAuthFlow (redirects to <id>.chromiumapp.org).
    permissions: ['storage', 'identity'],

    // Listing openrouter.ai here lets the background service worker call the API
    // without being subject to the page's CORS rules. Never widen this to <all_urls>.
    //
    // api.mikidev.app is ours, and is touched once per install: it issues the
    // trial key (#38) and, later, activates a licence (#39). Replies never go
    // there — every generation goes straight to openrouter.ai — so an outage on
    // our side cannot stop an install that already has a key.
    host_permissions: ['https://openrouter.ai/*', 'https://api.mikidev.app/*'],

    // `options_ui` is not set here on purpose. WXT generates it from the options
    // entrypoint and overrides whatever this config says, so `open_in_tab` lives
    // in a meta tag in entrypoints/options/index.html instead.
  }),
});
