import { defineConfig } from 'wxt';
import tailwindcss from '@tailwindcss/vite';

// See https://wxt.dev/api/config.html
export default defineConfig({
  modules: ['@wxt-dev/module-react'],

  vite: (env) => ({
    plugins: [tailwindcss()],

    oxc: {
      jsx: {
        // Vite 8 transforms JSX with oxc, and @vitejs/plugin-react does not set
        // `development` — oxc then defaults to the dev transform even in a
        // production build. That emits `jsxDEV()` calls, but React's
        // `jsx-dev-runtime` is an empty stub once NODE_ENV is production, so
        // every component throws "jsxDEV is not a function" on first render.
        // The dev transform also bakes absolute source paths into the bundle.
        development: env.mode !== 'production',
      },
    },
  }),

  manifest: {
    name: 'Reply AI — YouTube Comment Assistant',
    description:
      'Generate replies to YouTube comments in your own voice. Bring your own OpenRouter account.',
    version: '0.1.0',

    // Pins the extension ID to lbldodejinpgfnoaficdhaglkbhnkmlb. Without this an
    // unpacked extension's ID is derived from its directory path, and the OAuth
    // redirect URL (https://<id>.chromiumapp.org/) would change with it.
    // Generated by scripts/generate-key.mjs; the private half lives in .keys/.
    // Replace with the store-assigned key after the first Web Store upload.
    key: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2ux27q6d25ii39Jjk8EBogWJ3M0DtFCUAWrKo9jWJmluilWMF0VcnYa/7dEHNONJ7P14lwRc7GichBksk0LH3/y44pQyBvk5kimdnaAgpgtrBrhEHTOZlP8tfhS8A78RQc9G8mDlPr2ctJHrUXYOz+VUrYuViLZvCWJnxI3O3y0C5MCA+rcb7bSGcfXj1Gy2jRgkrHsH6aTQRD5mY0qQYtk1qHMq/Fd06hM5Ne3//ulKRqKTFzghK/Z6bqu5VxtGxRBtMm8RQiCTS031kpnVluzetvzXxLc84BKEJNtsS95W4bnHCzzvOGVqvM1ki/A20yd2wJ6Egrq9rnBYb7ICsQIDAQAB',

    // `identity` is needed for the OpenRouter OAuth PKCE flow via
    // chrome.identity.launchWebAuthFlow (redirects to <id>.chromiumapp.org).
    permissions: ['storage', 'identity'],

    // Listing openrouter.ai here lets the background service worker call the API
    // without being subject to the page's CORS rules. Never widen this to <all_urls>.
    host_permissions: ['https://openrouter.ai/*'],

    // `options_ui` is not set here on purpose. WXT generates it from the options
    // entrypoint and overrides whatever this config says, so `open_in_tab` lives
    // in a meta tag in entrypoints/options/index.html instead.
  },
});
